modLoader = "javafml"
loaderVersion="${forge_version_range}"
issueTrackerURL="${issue_tracker_url}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://api.modrinth.com/updates/${modrinth_project}/forge_updates.json"
displayURL="https://modrinth.com/mod/${modrinth_project}"
logoFile = "icon.png"
authors = "Zeitheron"

description = '''
Implementing handy features for Botania!
'''

displayTest="MATCH_VERSION"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange="${forge_version_range}"
ordering = "NONE" # NONE/BEFORE/AFTER
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange="${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "hammerlib"
mandatory = true
versionRange="[${hl_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "botania"
mandatory = true
versionRange = "[1.20.1-441-FORGE,)"
ordering = "AFTER"
side = "BOTH"
